# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Script3.py
# Created on: 2016-03-21 14:05:27.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
multiplied_reclass = "multiplied_reclass"
Q2 = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\Q2"
Q50 = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\Q50"
Q100 = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\Q100"
Q25 = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\Q25"
Q10 = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\Q10"
Q5 = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\Q5"

# Process: Raster Calculator (7)
arcpy.gp.RasterCalculator_sa("28.5*(44.221127**0.380)*(\"%multiplied_reclass%\"**0.436)*((144*44.221127**0.691)**0.338)", Q2)

# Process: Raster Calculator (8)
arcpy.gp.RasterCalculator_sa("(28.5*(44.221127)**0.380)*(\"%multiplied_reclass%\"**0.436)*((581*44.221127**0.650)**0.338)", Q50)

# Process: Raster Calculator (9)
arcpy.gp.RasterCalculator_sa("28.5*((44.221127)**0.380)*(\"%multiplied_reclass%\"**0.436)*((719*44.221127**0.643)**0.338)", Q100)

# Process: Raster Calculator (10)
arcpy.gp.RasterCalculator_sa("28.5*((44.221127)**0.380)*(\"%multiplied_reclass%\"**0.436)*((467*44.221127**0.655)**0.338)", Q25)

# Process: Raster Calculator (11)
arcpy.gp.RasterCalculator_sa("28.5*((44.221127)**0.380)*(\"%multiplied_reclass%\"**0.436)*((334*44.221127**0.665)**0.338)", Q10)

# Process: Raster Calculator (12)
arcpy.gp.RasterCalculator_sa("28.5*((44.221127)**0.380)*(\"%multiplied_reclass%\"**0.436)*((248*44.221127**0.670)**0.338)", Q5)

