# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Script2.py
# Created on: 2016-03-08 15:25:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
DEM = "DEM"
AnalysisMask = "AnalysisMask"
Analysismask_raster = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\Analysismask_raster"
filled_DEM = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\filled_DEM"
Output_drop_raster = ""
flow_direction = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\flow_direction"
flow_accum = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\flow_accum"
Multipied_accum = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\Multipied_accum"
Reclassed_raster = "\\\\hd.ad.syr.edu\\02\\04e4df\\Documents\\Desktop\\GISModeling\\Lab6\\Lab06Data.gdb\\Reclassed_raster"

# Process: Feature to Raster
arcpy.FeatureToRaster_conversion(AnalysisMask, "mask", Analysismask_raster, DEM)

# Process: Fill
tempEnvironment0 = arcpy.env.mask
arcpy.env.mask = Analysismask_raster
arcpy.gp.Fill_sa(DEM, filled_DEM, "")
arcpy.env.mask = tempEnvironment0

# Process: Flow Direction
arcpy.gp.FlowDirection_sa(filled_DEM, flow_direction, "NORMAL", Output_drop_raster)

# Process: Flow Accumulation
arcpy.gp.FlowAccumulation_sa(flow_direction, flow_accum, "", "FLOAT")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("\"%flow_accum%\"*(40*40)/43560", Multipied_accum)

# Process: Reclassify
arcpy.gp.Reclassify_sa(Multipied_accum, "Value", "0 591 0;591.00000009999997 999999999 1", Reclassed_raster, "DATA")

